ci:
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'ci(pre-commit): pre-commit.ci autoupdate'
  autofix_commit_msg: 'ci(pre-commit): pre-commit.ci autofixes'


repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.5.3
    hooks:
    - id: autoflake

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        files: pytest_rich\/.+\.py
        args: [--never]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.0.0
    hooks:
      - id: flakeheaven

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        language_version: python3.10
        additional_dependencies: [types-attrs]
